[dependencies]
tonic = "0.7"
prost = "0.10"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["derive"] }
influxdb = { version = "0.5", features = ["derive"] }
tokio = { version = "1.0", features = ["full"]}
